Ext.define('Desktop.model.CardGridView', {
	extend: 'Ext.data.Model',

	requires: [
		'Ext.data.field.Field'
	],

	fields	: [
		{name : 'creditCardId'},
		{name : 'applicationNumber'},
		{name : 'ccTrackingNumber', type: 'string'},
		{name : 'cardTypeKey'},
		{name : 'bpNo'},
		{name : 'stateDisplayLabel'},
		{name : 'createDate'},
		{name : 'legalEntityName'},
		{name : 'customerName'},
		{name : 'accountNo'},
		{name : 'applicantAskingLimit'},
		{name : 'interestRate'},
		{name : 'mobile'},		
		{name : 'customerId'},
		{name : 'idCustomerTypeKey'},
		{name : 'nid'},
		{name : 'tin'},
		{name : 'approvedLimit'},
		{name : 'dateOfBirth'},
		{name : 'designation'},
		{name : 'joiningDate'},
		{name : 'permanentAddr'},
		{name : 'officeAddr'},
		{name : 'maritalStatus'},
		{name : 'motherName'},
		{name : 'fatherName'},
		{name : 'spouse'},
		{name : 'creatorName'},
		{name : 'dataSource'},
		{name : 'district'},
		{name : 'division'},
		{name : 'currentStateName'},
		{name : 'actionName'},
		{name : 'userName'},
	    {name : 'cardGroupId'},
	    {name : 'cardGroupCreator'},
	    {name : ' inGroup'},
	    {name : 'dobOfGroupCreate'},
	    {name : 'staffId'},
	    {name : 'sourceBrance'},
	    {name : 'totalGroupAmount'},
	    {name : 'totalLoanThisGroup'},
	    {name : 'hoCrmComment'},
	    {name : 'cadComment'},
	    {name : 'loginName'},
	    {name : 'idGroupStateKey'},
	    {name : 'stateId'},
	]
});
