Ext.define('Desktop.model.CreditCard', {
	extend: 'Desktop.model.BaseModel',

	requires: [
		'Ext.data.field.Field'
	],

	fields	: [
		{name : 'cardTypeKey'									, type: 'int'},
		{name : 'creatorKey'									, type: 'int'},
		{name : 'customerKey'									, type: 'int'},
		{name : 'ccTrackingNumber'								, type: 'number'},
		{name : 'additionalIncomeAmount'						, type: 'number'},
		{name : 'allowedMuiltiplier'							, type: 'number'},
		{name : 'amoutDepositeCbbl'								, type: 'number'},
		{name : 'applicantAskingLimit'							, type: 'number'},
		{name : 'appliedCardMinBill'							, type: 'number'},
		{name : 'approvedLimit'									, type: 'number'},
		{name : 'autoDebitAmount'								, type: 'string'},
		{name : 'autoDebitReqMinAmount'							, type: 'number'},
		{name : 'cardProposedLimit'								, type: 'number'},
		{name : 'disposableIncome'								, type: 'number'},
		{name : 'existingLoanEmi'								, type: 'number'},
		{name : 'interestRate'									, type: 'number'},
		{name : 'maxAllowdLimit'								, type: 'number'},
		{name : 'maximumAllowedDbr'								, type: 'number'},
		{name : 'minimumPayment'								, type: 'number'},
		{name : 'preApprovedLimitLower'							, type: 'number'},
		{name : 'preApprovedLimitedUpper'						, type: 'number'},
		{name : 'proposedDbr'									, type: 'number'},
		{name : 'remainingAmountAfterPaidEmi'					, type: 'number'},
		{name : 'remainingEmi'									, type: 'number'},
		{name : 'salaryDepositedLastMonth'		       		 	, type: 'number'},
		{name : 'totalEmi'										, type: 'number'},
		{name : 'totalEmiPaidInCbbl'							, type: 'number'},
		{name : 'totalIncome'	        						, type: 'number'},
		{name : 'cardDeliveryFrom' 								, type: 'date'},
		{name : 'cibGeneration'       							, type: 'date'},
		{name : 'proposedBillingDate'    						, type: 'date'},
		{name : 'createDate'       								, type: 'date'},
		{name : 'accountNo' 									, type: 'string'},
		{name : 'additionalIncomeSource' 						, type: 'string'},
		{name : 'applicationNumber'								, type: 'string'},
		{name : 'autoDebitReqFullOutstanding'					, type: 'string'},
		{name : 'btCreditCardOutstanding'						, type: 'string'},
		{name : 'btRequestConcerBankName' 						, type: 'string'},
		{name : 'cardDuplicationReason'							, type: 'string'},
		{name : 'cardDuplicationResult'    						, type: 'string'},
		{name : 'cardMonthlyBilDebitedFrom' 					, type: 'string'},
		{name : 'cardSecurityType'    	        				, type: 'string'},
		{name : 'cibStatus'	    								, type: 'string'},
		{name : 'currentTypeBasedOnCardNature'				    , type: 'string'},
		{name : 'dataSource'           							, type: 'string'},	
		{name : 'declaration'									, type: 'string'},
		{name : 'duplications'    								, type: 'string'},
		{name : 'gpfLoan' 										, type: 'string'},
		{name : 'individualDeclaration'    	       				, type: 'string'},
		{name : 'kycLevel'	    								, type: 'string'},
		{name : 'loanToValue'				    				, type: 'string'},
		{name : 'maximumAllowedMultiplier'           			, type: 'string'},
		{name : 'netMonthlyIncome'								, type: 'string'},
		{name : 'ofacSanctionReason'    						, type: 'string'},
		{name : 'ofacSanctionResult' 							, type: 'string'},
		{name : 'sourceBranch'    	        					, type: 'string'},
		{name : 'sourcingStaffId'	    						, type: 'string'},
		{name : 'unSanctionReason'				    			, type: 'string'},
		{name : 'unSanctionResult'           					, type: 'string'},
		{name : 'valueOfSecurity'           					, type: 'string'},
		{name : 'autoDebitReqMinimumAmount'						, type: 'string'},
		{name : 'duplicationAreas'    							, type: 'string'},
	]

});