NID SERVICE TABLE :

USE [NID_UAT]
GO

TABLE name : T_NID_V2
Table column :

          
      ,[tx_nid]
      ,[tx_nid_pin]
      ,[tx_name_bangla]
      ,[tx_name_english]
      ,[dtt_dob]
      ,[tx_father_name]
      ,[tx_mother_name]
      ,[tx_spouse_name]
      ,[tx_occupation_name]
      ,[tx_present_district]
      ,[tx_present_division]
      ,[tx_present_rmo]
      ,[tx_present_municipality]
      ,[tx_present_upozila]
      ,[tx_present_union]
      ,[tx_present_moholla]
      ,[tx_present_add_moholla]
      ,[tx_present_ward_union_porishod]
      ,[tx_present_village]
      ,[tx_present_add_village]
      ,[tx_present_home]
      ,[tx_present_post_office]
      ,[tx_present_postal_code]
      ,[tx_present_region]
      ,[tx_permanent_district]
      ,[tx_permanent_division]
      ,[tx_permanent_rmo]
      ,[tx_permanent_municipality]
      ,[tx_permanent_upozila]
      ,[tx_permanent_union]
      ,[tx_permanent_moholla]
      ,[tx_permanent_add_moholla]
      ,[tx_permanent_ward_union_porishod]
      ,[tx_permanent_village]
      ,[tx_permanent_add_village]
      ,[tx_permanent_home]
      ,[tx_permanent_post_office]
      ,[tx_permanent_postal_code]
      ,[tx_permanent_region]
      ,[tx_blood_group]
      ,[tx_request_id]
      ,[tx_nid_image_path]
      ,[tx_nid_image_name]
      ,[tx_person_image_path]
      ,[tx_person_image_name]
      ,[tx_nid_image_public_path]
      ,[tx_person_image_public_path]
      ,[dtt_extract_time]
      ,[int_success]
   
GO

//////LMS NID DATABASE TABLE


/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id_nid_information_key]
      ,[id_nid_information_ver]
      ,[is_active]
      ,[id_env_key]
      ,[id_user_mod_key]
      ,[dtt_mod]
      ,[id_event_key]
      ,[id_state_key]
      ,[id_action_key]
      ,[id_nid_request_key]
      ,[tx_nid]
      ,[tx_nid_pin]
      ,[tx_name_bangla]
      ,[tx_name_english]
      ,[dtt_dob]
      ,[tx_father_name]
      ,[tx_mother_name]
      ,[tx_spouse_name]
      ,[tx_occupation_name]
      ,[tx_present_district]
      ,[tx_present_division]
      ,[tx_present_rmo]
      ,[tx_present_municipality]
      ,[tx_present_upozila]
      ,[tx_present_union]
      ,[tx_present_moholla]
      ,[tx_present_add_moholla]
      ,[tx_present_ward_union_porishod]
      ,[tx_present_village]
      ,[tx_present_add_village]
      ,[tx_present_home]
      ,[tx_present_post_office]
      ,[tx_present_postal_code]
      ,[tx_present_region]
      ,[tx_permanent_district]
      ,[tx_permanent_division]
      ,[tx_permanent_rmo]
      ,[tx_permanent_municipality]
      ,[tx_permanent_upozila]
      ,[tx_permanent_union]
      ,[tx_permanent_moholla]
      ,[tx_permanent_add_moholla]
      ,[tx_permanent_ward_union_porishod]
      ,[tx_permanent_village]
      ,[tx_permanent_add_village]
      ,[tx_permanent_home]
      ,[tx_permanent_post_office]
      ,[tx_permanent_postal_code]
      ,[tx_permanent_region]
      ,[tx_blood_group]
      ,[tx_request_id]
      ,[tx_nid_image_path]
      ,[tx_nid_image_name]
      ,[tx_person_image_path]
      ,[tx_person_image_name]
      ,[tx_nid_image_public_path]
      ,[tx_person_image_public_path]
      ,[dtt_extract_time]
  FROM [LMS_DEV].[dbo].[T_NID_INFORMATION]


