Ext.define('Desktop.view.loan.SearchNidForm', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.SearchNidForm',
    itemId: 'SearchNidForm',
    reference: 'SearchNidForm',
    requires: [
        'appConstants',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.toolbar.Toolbar',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Radio',
        'Ext.grid.Panel',
        'Ext.grid.column.Column',
        'Ext.grid.filters.filter.Number',
        'Ext.grid.column.Date',
        'Ext.grid.filters.filter.Date',
        'Ext.grid.filters.filter.String',
        'Ext.grid.filters.filter.Boolean',
        'Ext.selection.CheckboxModel',
        'Ext.grid.filters.Filters',
        'Ext.selection.CellModel'
    ],
    controller: 'loanPanel',

	closable : true,
	floating : true,
	width : 1000,
	height :600,
	modal: true,
	autoScroll: true,
    maximizable: true,
    alwaysOnTop: true,
    layout: 'fit',
	dockedItems: [{
            xtype: 'toolbar',
            dock: 'top',
            shadow: true,
            itemId: 'nidSearchTollbar',
            layout: 'column',
            columnWidth: 1,
            items : [{
                xtype : 'panel',
                itemId: 'nidSearchPad',
                reference: 'nidSearchPad',
                collapsed: false,
                columnWidth: 1,
                layout: 'column',
                border : false,
                title: 'Search',
                dockedItems : [{
                    xtype: 'toolbar',
                    dock: 'bottom',
                    itemId: 'nidSearchTollbar',
                    items : [
                        '->',
                        {
                            xtype: 'button',
                            text: 'Search',
                            margin : '4 4 4 4',
                            listeners: {
                                click: 'onClickSearchNid'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Compare',
                            margin : '4 4 4 4',
                            listeners: {
                                click: 'onClickCompareNid'
                            }
                        },
                        {
                            xtype: 'button',
                            text: 'Clean',
                            margin : '4 4 4 4',
                            listeners: {
                                click: 'onClickClearNid'
                            }
                        },
                        '->',
                    ]
                }],
                items: [{
                    xtype: 'textfield',
                    itemId: 'searchNidNumber',
                    reference: 'searchNidNumber',
                    fieldLabel: 'Nid Number'+ '<span class="req" style="color:red">*</span>',
                    columnWidth: 0.45,
                    labelAlign: 'left',
                    labelWidth: 100,
                    margin : '5 5 5 120',
                },
                {
                    xtype: 'datefield',
                    columnWidth: 0.40,
                    itemId: 'searchDateOfBirth',
                    reference: 'searchDateOfBirth',
                    fieldLabel: 'Date Of Birth'+ '<span class="req" style="color:red">*</span>',
                    labelAlign: 'left',
                    emptyText: 'To Date',
                    labelWidth: 100,
                    margin : '5 5 5 35',
                    format: 'd M Y',
                }]
            }]
        },
        {
            xtype: 'toolbar',
            dock: 'bottom',
            items : [
                '->',
                {
                    xtype: 'button',
                    text: 'Close',
                    listeners: {
                        click: 'onClickNidViewCloseBtn'
                    }
                },
                '->',
            ]
        }],
        items: [{
            xtype: 'fieldset',
            itemId: 'nidInformation',
            reference: 'nidInformation',
            collapsible: true,
            collapsed: true,
            columnWidth: 1,
            layout: 'column',
            title: 'NID INFORMATION',
            margin: '10 10 10 10',
            items: [
                {
                    xtype : 'form',
                    itemId: 'nidSideInformationForm',
                    reference: 'nidSideInformationForm',
                    collapsible: false,
                    title: 'NID Detalis',
                    collapsed: false,
                    columnWidth: .5,
                    layout: 'column',
                    height :400,
                    border : false,
                    autoHeight: true,             
                    scrollable: true,
                    autoScroll: true,
                    items: [
                        {
                            xtype: 'textfield',
                            itemId: 'nidNo',
                            reference: 'nidNo',
                            fieldLabel: 'Nid No',
                            columnWidth: .70,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 120,
                            margin : '5 10 5 10',
                        },                        
                        {
                            xtype: 'textfield',
                            itemId: 'nameOfBangla',
                            reference: 'nameOfBangla',
                            fieldLabel: 'Name In Bangla',
                            columnWidth: .70,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 120,
                            margin : '-63 10 5 10',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'nameOfEnglish',
                            reference: 'nameOfEnglish',
                            fieldLabel: 'Name In English',
                            columnWidth: .70,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 120,
                            margin : '-30 10 5 10',
                        },
                        {
                            xtype: 'datefield',
                            itemId: 'dateOfBirth',
                            reference: 'dateOfBirth',
                            fieldLabel: 'Date Of Birth',
                            columnWidth: 1,
                            labelAlign: 'left',
                           // readOnly : true,
                            labelWidth: 120,
                            format: 'd M Y',
                            margin : '5 10 5 10',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'fatherName',
                            reference: 'fatherName',
                            fieldLabel: 'Father Name',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 120,
                            margin : '5 10 5 10',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'motherName',
                            reference: 'motherName',
                            fieldLabel: 'Mother Name',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 120,
                            margin : '5 10 5 10',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'spouseName',
                            reference: 'spouseName',
                            fieldLabel: 'Spouse Name',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 120,
                            margin : '5 10 5 10',
                        },                        
                        {
                            xtype: 'textfield',
                            itemId: 'occupation',
                            reference: 'occupation',
                            fieldLabel: 'Occupation',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 120,
                            margin : '5 10 5 10',
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Present Address',
                            margin : '5 10 5 10',
                            columnWidth: 1,
                            labelAlign: 'left',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'presentDistrict',
                            reference: 'presentDistrict',
                            fieldLabel: 'District',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'presentDivision',
                            reference: 'presentDivision',
                            fieldLabel: 'Division',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'presentRmo',
                            reference: 'presentRmo',
                            fieldLabel: 'Rmo',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'presentMunicipality',
                            reference: 'presentMunicipality',
                            fieldLabel: 'Municipality',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'presentUpozila',
                            reference: 'presentUpozila',
                            fieldLabel: 'Upozila',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },                        
                        {
                            xtype: 'textfield',
                            itemId: 'presentUnion',
                            reference: 'presentUnion',
                            fieldLabel: 'Union',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'presentMoholla',
                            reference: 'presentMoholla',
                            fieldLabel: 'Moholla',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'presentAddMoholla',
                            reference: 'presentAddMoholla',
                            fieldLabel: 'Add Moholla',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'presentWardUnionPorishod',
                            reference: 'presentWardUnionPorishod',
                            fieldLabel: 'Ward Union Porishod',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'presentVillage',
                            reference: 'presentVillage',
                            fieldLabel: 'Village',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'presentAddVillage',
                            reference: 'presentAddVillage',
                            fieldLabel: 'Add Village',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },                        
                        {
                            xtype: 'textfield',
                            itemId: 'presentHome',
                            reference: 'presentHome',
                            fieldLabel: 'Home',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'presentPostOffice',
                            reference: 'presentPostOffice',
                            fieldLabel: 'Post Office',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },                      
                        {
                            xtype: 'textfield',
                            itemId: 'presentPostalCode',
                            reference: 'presentPostalCode',
                            fieldLabel: 'Postal Code',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'presentRegion',
                            reference: 'presentRegion',
                            fieldLabel: 'Region',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },
                        {
                            xtype: 'displayfield',
                            fieldLabel: 'Permanent Address',
                            margin : '5 10 5 10',
                            columnWidth: 1,
                            labelWidth: 120,
                            labelAlign: 'left',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'permanentDistrict',
                            reference: 'permanentDistrict',
                            fieldLabel: 'District',                           
                            labelAlign: 'left',
                            readOnly : true,
                            columnWidth: .55,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },                        
                        {
                            xtype: 'textfield',
                            itemId: 'permanentDivision',
                            reference: 'permanentDivision',
                            fieldLabel: 'Division',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'permanentRmo',
                            reference: 'permanentRmo',
                            fieldLabel: 'Rmo',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'permanentMunicipality',
                            reference: 'permanentMunicipality',
                            fieldLabel: ' Municipality',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'permanentUpozila',
                            reference: 'permanentUpozila',
                            fieldLabel: ' Upozila',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'permanentUnion',
                            reference: 'permanentUnion',
                            fieldLabel: ' Union',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'permanentMoholla',
                            reference: 'permanentMoholla',
                            fieldLabel: ' Moholla',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },                        
                        {
                            xtype: 'textfield',
                            itemId: 'permanentAddMoholla',
                            reference: 'permanentAddMoholla',
                            fieldLabel: ' Add Moholla',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'permanentWardUnionPorishod',
                            reference: 'permanentWardUnionPorishod',
                            fieldLabel: ' Ward Union Porishod',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'permanentVillage',
                            reference: 'permanentVillage',
                            fieldLabel: ' Village',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'permanentAddVillage',
                            reference: 'permanentAddVillage',
                            fieldLabel: ' Add Village',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'permanentHome',
                            reference: 'permanentHome',
                            fieldLabel: ' Home',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'permanentPostOffice',
                            reference: 'permanentPostOffice',
                            fieldLabel: ' PostOffice',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },                        
                        {
                            xtype: 'textfield',
                            itemId: 'permanentPostalCode',
                            reference: 'permanentPostalCode',
                            fieldLabel: ' PostalCode',
                            columnWidth: .45,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 70,
                            margin : '5 10 5 13',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'permanentRegion',
                            reference: 'permanentRegion',
                            fieldLabel: ' Region',
                            columnWidth: .55,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 77,
                            margin : '5 0 5 55',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'bloodGroup',
                            reference: 'bloodGroup',
                            fieldLabel: 'Blood Group',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 120,
                            margin : '5 10 5 10',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'nidPin',
                            reference: 'nidPin',
                            fieldLabel: 'Nid Pin',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 120,
                            margin : '5 10 5 10',
                        },                                                                    
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Person Image',
                            itemId: 'personImage',
                            reference: 'personImage',
                            columnWidth: .80,
                            labelAlign: 'left',
                            labelWidth: 120,
                            readOnly: true,
                            value: 'Click For Person Image Show',
                            margin: '5 10 5 10',
                            hidden: true,
                        },
                        {
                            xtype: 'button',
                            columnWidth: .20,
                            margin: '5 10 5 0',
                            itemId: 'personImageButton',
                            reference: 'personImageButton', 
                            iconCls : 'view_icon',
                            tooltip: 'View File',
                            hidden: true,
                            handler: 'onClickPersonViewImage'
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 1,
                            margin: '5 10 5 0',
                            itemId: 'personImagePath',
                            reference: 'personImagePath', 
                            readOnly : true,
                            hidden: true,
                        },
                        {
                            xtype: 'textfield',
                            fieldLabel: 'Nid Image',
                            itemId: 'nidImage',
                            reference: 'nidImage',
                            columnWidth: .80,
                            labelAlign: 'left',
                            labelWidth: 120,
                            readOnly: true,
                            value: 'Click For Nid Image Show',
                            margin: '5 10 5 10',
                            hidden: true,
                        },
                        {
                            xtype: 'button',
                            columnWidth: .20,
                            margin: '5 10 5 0',
                            itemId: 'nidImageButton',
                            reference: 'nidImageButton', 
                            iconCls : 'view_icon',
                            tooltip: 'View File',
                            hidden: true,
                            handler: 'onClickNidViewImage'
                        },
                        {
                            xtype: 'textfield',
                            columnWidth: 1,
                            margin: '5 10 5 0',
                            itemId: 'nidImagePath',
                            reference: 'nidImagePath', 
                            readOnly : true,
                            hidden: true,
                        },
                        {
                            xtype: 'textareafield',
                            itemId: 'comments',
                            reference: 'comments',
                            fieldLabel: 'Comments',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 120,
                            margin : '5 10 5 10',
                        },
                    ]
                },
                {
                    xtype : 'form',
                    itemId: 'lmsSideInformationForm',
                    reference: 'lmsSideInformationForm',
                    title: 'LMS Detalis',
                    collapsible: false,
                    collapsed: false,
                    columnWidth: .5,
                    height :400,
                    layout: 'column',
                    border : false,
                    autoHeight: true,             
                    scrollable: true,
                    autoScroll: true,
                    hidden: true,
                    items: [
                         {
                            xtype: 'textfield',
                            itemId: 'lmsNidNo',
                            reference: 'lmsNidNo',
                            fieldLabel: 'Nid No',
                            columnWidth: .70,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 150,
                            margin : '5 10 5 10',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'lmsNameOfBangla',
                            reference: 'lmsNameOfBangla',
                            fieldLabel: 'Name In Bangla',
                            columnWidth: .70,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 150,
                            margin : '5 10 5 10',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'lmsNameOfEnglish',
                            reference: 'lmsNameOfEnglish',
                            fieldLabel: 'Name In English',
                            columnWidth: .70,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 150,
                            margin : '5 10 5 10',
                        },
                        {
                            xtype: 'datefield',
                            itemId: 'lmsDateOfBirth',
                            reference: 'lmsDateOfBirth',
                            fieldLabel: 'Date Of Birth',
                            columnWidth: 1,
                            labelAlign: 'left',
                           // readOnly : true,
                            labelWidth: 150,
                            format: 'd M Y',
                            margin : '5 10 5 10',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'lmsFatherName',
                            reference: 'lmsFatherName',
                            fieldLabel: 'Father Name',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 150,
                            margin : '5 10 5 10',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'lmsMotherName',
                            reference: 'lmsMotherName',
                            fieldLabel: 'Mother Name',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 150,
                            margin : '5 10 5 10',
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'lmsspouseName',
                            reference: 'lmsspouseName',
                            fieldLabel: 'Spouse Name',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 150,
                            margin : '5 10 5 10',
                        },    
                        {
                            xtype: 'textfield',
                            itemId: 'lmsBloodGroup',
                            reference: 'lmsBloodGroup',
                            fieldLabel: 'Blood Group',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 150,
                            margin : '5 10 5 10',
                        },  
                        {
                            xtype: 'textfield',
                            itemId: 'presentAddress',
                            reference: 'presentAddress',
                            fieldLabel: 'Present Address',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 150,
                            margin : '5 10 5 10',
                        },
                        {
                            xtype: 'textareafield',
                            itemId: 'permanentAddr',
                            reference: 'permanentAddr',
                            fieldLabel: 'Permanent Address',
                            columnWidth: 1,
                            labelAlign: 'left',
                            readOnly : true,
                            labelWidth: 150,
                            margin : '5 10 5 10',
                        },                                       
                    ]
                }
            ]
        }],
        listeners: {
            afterrender: 'onActivateSearchNid'
        }
});


function getImagePosition(){
    var changingImage = Ext.create('Ext.Img', {       
        reference: 'nidPersonImageView',
        width: 184,
        height: 90,
        columnWidth: .30,
        src: '',
        margin : '5 10 5 10',
        renderTo: Ext.getBody()
    });
    return changingImage;
}
function getLmsImagePosition(){
    var lmschangingImage = Ext.create('Ext.Img', {
        src: '',
        reference: 'lmsPersonImageView',
        width: 184,
        height: 90,
        columnWidth: .30,
        margin : '5 10 5 10',
        renderTo: Ext.getBody()
    });
    return lmschangingImage;
}